### ISSUE TITLE
Indirections and missing implementations

### ISSUE THREAD

**Issue by torarnv** [Vector35/workflow_objc#49] opened 2023-01-03 14:06 UTC
This may be a dyld-cache extractor issue, but I'm seeing this:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/7536/210372931-d4df3dc1-a658-42f4-88ac-e3d5e96e2834.png">

Hopper has the same issue. Is there any way to follow the rabbit hole for these references to end up with the implementation?

**Comment by cxnder** [comment] 2023-01-03 14:54
Regarding the selector stub (which is the missing implementation here), we *should* be able to start resolving those soon; a working POC is on [`msgsend_stubs`](https://github.com/Vector35/workflow_objc/tree/msgsend_stubs).

Being able to actually follow and check this implementation will block on https://github.com/Vector35/binaryninja-api/issues/290 as I don't know of any extractors currently that bother to actually pull out the stub code. 

Hopper will have this same issue as its cache support is simply a wrapper for xcode's built-in extractor from what I understand.

**Comment by cxnder** [comment] 2023-01-03 15:05
Duplicate of #15 and https://github.com/Vector35/binaryninja-api/issues/290

**Closed by cxnder** 2023-01-03 15:05 UTC
