### ISSUE TITLE
Cannot change type for variables

### ISSUE THREAD

**Issue by torarnv** [Vector35/workflow_objc#48] opened 2023-01-03 14:03 UTC
<img width="741" alt="image" src="https://user-images.githubusercontent.com/7536/210372465-ff527d8a-0b57-4bd3-b2dd-cd03286a7a6c.png">

**Comment by cxnder** [comment] 2023-01-03 15:04
* Duplicate of #47 as that class typedef will only exist if the objc info is parseable, and NSResponder was not parsed as shown by method names.
* It is worth noting that when it is functional, you wouldn't add the pointer to the type, just the type, as it's type-deffed to be a pointer to the struct. I'm aware that that's non-standard and confusing and will be changing it soon.

**Closed by cxnder** 2023-01-03 15:04 UTC
